package com.hillrom.vest.config;

public class NotificationTypeConstants {

	public static final String SETTINGS_DEVIATION = "SETTINGS_DEVIATION";
	public static String HMR_NON_COMPLIANCE = "HMR_NON_COMPLIANCE";
	public static String HMR_AND_SETTINGS_DEVIATION = HMR_NON_COMPLIANCE+" AND "+SETTINGS_DEVIATION;
	
	public static final String SETTINGS_DEVIATION_VEST = "SETTINGS_DEVIATION_VEST";
	public static String HMR_NON_COMPLIANCE_VEST = "HMR_NON_COMPLIANCE_VEST";
	public static final String SETTINGS_DEVIATION_MONARCH = "SETTINGS_DEVIATION_MONARCH";
	public static String HMR_NON_COMPLIANCE_MONARCH = "HMR_NON_COMPLIANCE_MONARCH";
	
	public static String HMR_AND_SETTINGS_DEVIATION_VEST = HMR_NON_COMPLIANCE+" AND "+SETTINGS_DEVIATION_VEST;	
	public static String HMR_AND_SETTINGS_DEVIATION_MONARCH = HMR_NON_COMPLIANCE+" AND "+SETTINGS_DEVIATION_MONARCH;
	public static String HMR_VEST_AND_SETTINGS_DEVIATION = HMR_NON_COMPLIANCE_VEST+" AND "+SETTINGS_DEVIATION;
	public static String HMR_MONARCH_AND_SETTINGS_DEVIATION = HMR_NON_COMPLIANCE_MONARCH+" AND "+SETTINGS_DEVIATION;	
	public static String HMR_MONARCH_AND_SETTINGS_DEVIATION_VEST = HMR_NON_COMPLIANCE_MONARCH+" AND "+SETTINGS_DEVIATION_VEST;
	public static String HMR_VEST_AND_SETTINGS_DEVIATION_VEST = HMR_NON_COMPLIANCE_VEST+" AND "+SETTINGS_DEVIATION_VEST;	
	public static String HMR_MONARCH_AND_SETTINGS_DEVIATION_MONARCH = HMR_NON_COMPLIANCE_MONARCH+" AND "+SETTINGS_DEVIATION_MONARCH;
	public static String HMR_VEST_AND_SETTINGS_DEVIATION_MONARCH = HMR_NON_COMPLIANCE_VEST+" AND "+SETTINGS_DEVIATION_MONARCH;
	
	public static String MISSED_THERAPY = "MISSED_THERAPY";
	public static String ADHERENCE_SCORE_RESET = "ADHERENCE_SCORE_RESET"; 
	
	public static String SETTINGS_DEVIATION_DISPLAY_VALUE = "Setting Deviation";
	public static String HMR_NON_COMPLIANCE_DISPLAY_VALUE = "Below Treatment Minutes";
	public static String HMR_AND_SETTINGS_DEVIATION_DISPLAY_VALUE = HMR_NON_COMPLIANCE+" and "+SETTINGS_DEVIATION;
	public static String MISSED_THERAPY_DISPLAY_VALUE = "Missed Therapy Days";
	public static String ADHERENCE_SCORE_RESET_DISPLAY_VALUE = "Adherence Score Reset";
	
	
	public static String SETTINGS_DEVIATION_VEST_DISPLAY_VALUE = "Setting Deviation(V)";
	public static String SETTINGS_DEVIATION_MONARCH_DISPLAY_VALUE = "Setting Deviation(M)";	
	public static String HMR_NON_COMPLIANCE_VEST_DISPLAY_VALUE = "Below Treatment Minutes(V)";
	public static String HMR_NON_COMPLIANCE_MONARCH_DISPLAY_VALUE = "Below Treatment Minutes(M)";	
	
}
