package com.hillrom.vest.repository.util;

public class QueryConstants {
	
	public static String QUERY_PATIENT_SEARCH_FOR_ALL_DEVICETYPE_HILLROM_LOGIN =
			 "  select patient_id as id,pemail,pfirstName,plastName, isDeleted,pzipcode,paddress,pcity,pdob,pgender,ptitle,"
				+" phillrom_id,createdAt,isActivated, state , adherence,last_date,mrnid,hName,clinicName,isExpired,isHMRNonCompliant,"
				+" isSettingsDeviated, isMissedTherapy,adherencesetting	from (select user.id as patient_id,user.email as pemail,"
				+" user.first_name as pfirstName,user.last_name as "
				+" plastName, user.is_deleted as isDeleted, user.zipcode as pzipcode,patInfo.address paddress,patInfo.city " 
				+" as pcity,user.dob as pdob, user.gender as pgender,user.title as ptitle,  user.hillrom_id as phillrom_id,"
				+" user.created_date as createdAt, user.activated as isActivated, patInfo.state as state , "
				+" user_clinic.mrn_id as mrnid, clinic.id as pclinicid,  GROUP_CONCAT(clinic.name) as clinicName, "
				+" user.expired as isExpired, pc.compliance_score as adherence,   pc.last_therapy_session_date as last_date, "
				+" pc.is_hmr_compliant as isHMRNonCompliant, pc.is_settings_deviated as isSettingsDeviated, "
				+" pc.missed_therapy_count as isMissedTherapy, clinic.adherence_setting as adherencesetting " 
				+" from USER user "
				+" join " 
				+" USER_PATIENT_ASSOC  upa on user.id = upa.user_id  and upa.relation_label = 'Self' join "
				+" PATIENT_INFO patInfo on upa.patient_id = patInfo.id "  
				+" left outer join "
				+" CLINIC_PATIENT_ASSOC user_clinic on user_clinic.patient_id = patInfo.id " 
				+" left outer join " 
				+" PATIENT_DEVICES_ASSOC patient_dev_assoc on patient_dev_assoc.patient_id = patInfo.id "  
				+" join " 
				+" USER_AUTHORITY user_authority on user_authority.user_id = user.id "  
				+" and user_authority.authority_name = 'PATIENT'  and (lower(user.first_name) like lower(:queryString) or "
				+" lower(user.last_name) like lower(:queryString) or  lower(user.email) like lower(:queryString) or "  
				+" lower(CONCAT(user.first_name,' ',user.last_name)) like lower(:queryString) or " 
				+" lower(CONCAT(user.last_name,' ',user.first_name)) like lower(:queryString) or "
				+" lower(user.hillrom_id) like lower(:queryString)) " 				
				+" left outer join PATIENT_COMPLIANCE_MONARCH pc on user.id = pc.user_id " 
				+" AND pc.date=IF(pc.date <> curdate(),subdate(curdate(),1),curdate()) " 
				+" left outer join CLINIC clinic on user_clinic.clinic_id = clinic.id and  user_clinic.patient_id = patInfo.id"  
				+" where patient_dev_assoc.device_type in ('MONARCH','ALL')   group by user.id) as associated_patient " 
				+" left outer join " 
				+" (select  GROUP_CONCAT(huser.last_name ,' ',huser.first_name ) as hName,  clinic.id as hclinicid " 
				+" from USER huser " 
				+" join USER_AUTHORITY user_authorityh on user_authorityh.user_id = huser.id"   
				+" and user_authorityh.authority_name = 'HCP' "  
				+" left outer join CLINIC_USER_ASSOC user_clinic " 
				+" on user_clinic.users_id = huser.id "  
				+" left outer join CLINIC clinic on user_clinic.clinics_id = clinic.id" 
				+" and user_clinic.users_id = huser.id"  
				+" left outer join PATIENT_COMPLIANCE_MONARCH pc on huser.id = pc.user_id " 
				+" AND pc.date=IF(pc.date <> curdate(),subdate(curdate(),1),curdate()) "  
				+" group by clinic.id) as associated_hcp "  
				+" on associated_patient.pclinicid = associated_hcp.hclinicid "
				+" UNION "
				+" select patient_id as id,pemail,pfirstName,plastName, isDeleted,pzipcode,paddress,pcity,pdob,pgender,ptitle, phillrom_id,createdAt,isActivated, " 
				+" state,adherence,last_date,mrnid,hName,clinicName,isExpired,isHMRNonCompliant,isSettingsDeviated, isMissedTherapy,adherencesetting "				
				+" from " 
				+" (select " 
				+" user.id as patient_id,user.email as pemail,user.first_name as pfirstName, "
				+" user.last_name as plastName, user.is_deleted as isDeleted, user.zipcode as pzipcode, "
				+" patInfo.address paddress,patInfo.city as pcity,user.dob as pdob, user.gender as pgender, "
				+" user.title as ptitle,  user.hillrom_id as phillrom_id,user.created_date as createdAt, "
				+" user.activated as isActivated, patInfo.state as state ,  user_clinic.mrn_id as mrnid, "
				+" clinic.id as pclinicid,  GROUP_CONCAT(clinic.name) as clinicName, user.expired as isExpired, "
				+" pc.compliance_score as adherence,   pc.last_therapy_session_date "
				+" as last_date,pc.is_hmr_compliant as isHMRNonCompliant, pc.is_settings_deviated "
				+" as isSettingsDeviated, pc.missed_therapy_count as isMissedTherapy, " 
				+" clinic.adherence_setting as adherencesetting " 
				+" from USER user " 
				+" join "
				+" USER_PATIENT_ASSOC  upa on user.id = upa.user_id  and upa.relation_label = 'Self' "
				+" join " 
				+" PATIENT_INFO patInfo on upa.patient_id = patInfo.id " 	
				+" left outer join " 
				+" CLINIC_PATIENT_ASSOC user_clinic on user_clinic.patient_id = patInfo.id " 
				+" left outer join " 
				+" PATIENT_DEVICES_ASSOC patient_dev_assoc on patient_dev_assoc.patient_id = patInfo.id " 
				+" join " 
				+" USER_AUTHORITY user_authority on user_authority.user_id = user.id "   
				+" and user_authority.authority_name = 'PATIENT'  and (lower(user.first_name) "
				+" like lower(:queryString) or  lower(user.last_name) like lower(:queryString) or  lower(user.email) " 
				+" like lower(:queryString) or  lower(CONCAT(user.first_name,' ',user.last_name)) like lower(:queryString) or " 
				+" lower(CONCAT(user.last_name,' ',user.first_name)) like lower(:queryString) or "
				+" lower(user.hillrom_id) like lower(:queryString)) "				
				+" left outer join " 
				+" PATIENT_COMPLIANCE pc on user.id = pc.user_id AND " 
				+" pc.date=IF(pc.date <> curdate(),subdate(curdate(),1),curdate())	"  
				+" left outer join " 
				+" CLINIC clinic on user_clinic.clinic_id = clinic.id and  user_clinic.patient_id = patInfo.id "		
				+" where patient_dev_assoc.device_type IN ('VEST','ALL') " 
				+" group by user.id) as associated_patient " 
				+" left outer join" 
				+" (select "  
				+" GROUP_CONCAT(huser.last_name ,' ',huser.first_name ) as hName, "  
				+" clinic.id as hclinicid " 
				+" from USER huser	" 
				+" join	" 
				+" USER_AUTHORITY user_authorityh on user_authorityh.user_id = huser.id  and user_authorityh.authority_name = 'HCP'	" 
				+" left outer join	" 
				+" CLINIC_USER_ASSOC user_clinic on user_clinic.users_id = huser.id	" 
				+" left outer join	" 
				+" CLINIC clinic on user_clinic.clinics_id = clinic.id and user_clinic.users_id = huser.id	"  
				+" left outer join	" 
				+" PATIENT_COMPLIANCE pc on huser.id = pc.user_id AND pc.date=IF(pc.date <> curdate(),subdate(curdate(),1),curdate())	"  
				+" group by clinic.id) as associated_hcp	"  
				+" on associated_patient.pclinicid = associated_hcp.hclinicid ";
	
	public static String QUERY_PATIENT_SEARCH_FOR_ALL_DEVICETYPE_CLINIC_ADMIN_LOGIN 
			= "  select patient_id as id,pemail,pfirstName,plastName, isDeleted,pzipcode,paddress,pcity,pdob,pgender,ptitle,"
				+" phillrom_id,createdAt,isActivated, state , adherence,last_date,mrnid,hName,clinicName,isExpired,isHMRNonCompliant,"
				+" isSettingsDeviated, isMissedTherapy,adherencesetting	from (select user.id as patient_id,user.email as pemail,"
				+" user.first_name as pfirstName,user.last_name as "
				+" plastName, user.is_deleted as isDeleted, user.zipcode as pzipcode,patInfo.address paddress,patInfo.city " 
				+" as pcity,user.dob as pdob, user.gender as pgender,user.title as ptitle,  user.hillrom_id as phillrom_id,"
				+" user.created_date as createdAt, user.activated as isActivated, patInfo.state as state , "
				+" user_clinic.mrn_id as mrnid, clinic.id as pclinicid,  GROUP_CONCAT(clinic.name) as clinicName, "
				+" user.expired as isExpired, pc.compliance_score as adherence,   pc.last_therapy_session_date as last_date, "
				+" pc.is_hmr_compliant as isHMRNonCompliant, pc.is_settings_deviated as isSettingsDeviated, "
				+" pc.missed_therapy_count as isMissedTherapy, clinic.adherence_setting as adherencesetting " 
				+" from USER user "
				+" join " 
				+" USER_PATIENT_ASSOC  upa on user.id = upa.user_id  and upa.relation_label = 'Self' join "
				+" PATIENT_INFO patInfo on upa.patient_id = patInfo.id "  
				+" left outer join "
				+" CLINIC_PATIENT_ASSOC user_clinic on user_clinic.patient_id = patInfo.id " 
				+" left outer join " 
				+" PATIENT_DEVICES_ASSOC patient_dev_assoc on patient_dev_assoc.patient_id = patInfo.id "  
				+" join " 
				+" USER_AUTHORITY user_authority on user_authority.user_id = user.id "  
				+" and user_authority.authority_name = 'PATIENT'  and (lower(user.first_name) like lower(:queryString) or "
				+" lower(user.last_name) like lower(:queryString) or  lower(user.email) like lower(:queryString) or "  
				+" lower(CONCAT(user.first_name,' ',user.last_name)) like lower(:queryString) or " 
				+" lower(CONCAT(user.last_name,' ',user.first_name)) like lower(:queryString) or "
				+" (lower(IFNULL(user_clinic.mrn_id,0)) like lower(:queryString) ) ) "
				+" left outer join PATIENT_COMPLIANCE_MONARCH pc on user.id = pc.user_id " 
				+" AND pc.date=IF(pc.date <> curdate(),subdate(curdate(),1),curdate()) " 
				+" left outer join CLINIC clinic on user_clinic.clinic_id = clinic.id and  user_clinic.patient_id = patInfo.id"  
				+" where patient_dev_assoc.device_type in ('MONARCH','ALL')   group by user.id) as associated_patient " 
				+" left outer join " 
				+" (select  GROUP_CONCAT(huser.last_name ,' ',huser.first_name ) as hName,  clinic.id as hclinicid " 
				+" from USER huser " 
				+" join USER_AUTHORITY user_authorityh on user_authorityh.user_id = huser.id"   
				+" and user_authorityh.authority_name = 'HCP' "  
				+" left outer join CLINIC_USER_ASSOC user_clinic " 
				+" on user_clinic.users_id = huser.id "  
				+" left outer join CLINIC clinic on user_clinic.clinics_id = clinic.id" 
				+" and user_clinic.users_id = huser.id"  
				+" left outer join PATIENT_COMPLIANCE_MONARCH pc on huser.id = pc.user_id " 
				+" AND pc.date=IF(pc.date <> curdate(),subdate(curdate(),1),curdate()) "  
				+" group by clinic.id) as associated_hcp "  
				+" on associated_patient.pclinicid = associated_hcp.hclinicid "
				+" UNION "
				+" select patient_id as id,pemail,pfirstName,plastName, isDeleted,pzipcode,paddress,pcity,pdob,pgender,ptitle, phillrom_id,createdAt,isActivated, " 
				+" state,adherence,last_date,mrnid,hName,clinicName,isExpired,isHMRNonCompliant,isSettingsDeviated, isMissedTherapy,adherencesetting "				
				+" from " 
				+" (select " 
				+" user.id as patient_id,user.email as pemail,user.first_name as pfirstName, "
				+" user.last_name as plastName, user.is_deleted as isDeleted, user.zipcode as pzipcode, "
				+" patInfo.address paddress,patInfo.city as pcity,user.dob as pdob, user.gender as pgender, "
				+" user.title as ptitle,  user.hillrom_id as phillrom_id,user.created_date as createdAt, "
				+" user.activated as isActivated, patInfo.state as state ,  user_clinic.mrn_id as mrnid, "
				+" clinic.id as pclinicid,  GROUP_CONCAT(clinic.name) as clinicName, user.expired as isExpired, "
				+" pc.compliance_score as adherence,   pc.last_therapy_session_date "
				+" as last_date,pc.is_hmr_compliant as isHMRNonCompliant, pc.is_settings_deviated "
				+" as isSettingsDeviated, pc.missed_therapy_count as isMissedTherapy, " 
				+" clinic.adherence_setting as adherencesetting " 
				+" from USER user " 
				+" join "
				+" USER_PATIENT_ASSOC  upa on user.id = upa.user_id  and upa.relation_label = 'Self' "
				+" join " 
				+" PATIENT_INFO patInfo on upa.patient_id = patInfo.id " 	
				+" left outer join " 
				+" CLINIC_PATIENT_ASSOC user_clinic on user_clinic.patient_id = patInfo.id " 
				+" left outer join " 
				+" PATIENT_DEVICES_ASSOC patient_dev_assoc on patient_dev_assoc.patient_id = patInfo.id " 
				+" join " 
				+" USER_AUTHORITY user_authority on user_authority.user_id = user.id "   
				+" and user_authority.authority_name = 'PATIENT'  and (lower(user.first_name) "
				+" like lower(:queryString) or  lower(user.last_name) like lower(:queryString) or  lower(user.email) " 
				+" like lower(:queryString) or  lower(CONCAT(user.first_name,' ',user.last_name)) like lower(:queryString) or " 
				+" lower(CONCAT(user.last_name,' ',user.first_name)) like lower(:queryString) or "
				+" (lower(IFNULL(user_clinic.mrn_id,0)) like lower(:queryString) ) ) "			
				+" left outer join " 
				+" PATIENT_COMPLIANCE pc on user.id = pc.user_id AND " 
				+" pc.date=IF(pc.date <> curdate(),subdate(curdate(),1),curdate())	"  
				+" left outer join " 
				+" CLINIC clinic on user_clinic.clinic_id = clinic.id and  user_clinic.patient_id = patInfo.id "		
				+" where patient_dev_assoc.device_type IN ('VEST','ALL') " 
				+" group by user.id) as associated_patient " 
				+" left outer join" 
				+" (select "  
				+" GROUP_CONCAT(huser.last_name ,' ',huser.first_name ) as hName, "  
				+" clinic.id as hclinicid " 
				+" from USER huser	" 
				+" join	" 
				+" USER_AUTHORITY user_authorityh on user_authorityh.user_id = huser.id  and user_authorityh.authority_name = 'HCP'	" 
				+" left outer join	" 
				+" CLINIC_USER_ASSOC user_clinic on user_clinic.users_id = huser.id	" 
				+" left outer join	" 
				+" CLINIC clinic on user_clinic.clinics_id = clinic.id and user_clinic.users_id = huser.id	"  
				+" left outer join	" 
				+" PATIENT_COMPLIANCE pc on huser.id = pc.user_id AND pc.date=IF(pc.date <> curdate(),subdate(curdate(),1),curdate())	"  
				+" group by clinic.id) as associated_hcp	"  
				+" on associated_patient.pclinicid = associated_hcp.hclinicid ";

}
