var roleEnum = {
  ADMIN : 'ADMIN',
  PATIENT : 'PATIENT',
  HCP : 'HCP',
  ACCT_SERVICES : 'ACCT_SERVICES',
  ASSOCIATES : 'ASSOCIATES',
  HILLROM_ADMIN : 'HILLROM_ADMIN',
  CLINIC_ADMIN : 'CLINIC_ADMIN',
  ANONYMOUS : 'ANONYMOUS'
};

var doctorsAvailInClinic = 
	{
    "hcpUsers": [
        {
	        "id": 101,
	        "title": "Mr.",
	        "firstName": "Rishabh",
	        "middleName": "A",
	        "lastName": "Jain",
	        "email": "rishabhjain+acct5@neevtech.com",
	        "gender": "M",
	        "zipcode": 560042,
	        "activated": false,
	        "langKey": "en",
	        "resetKey": null,
	        "resetDate": null,
	        "termsConditionAccepted": false,
	        "termsConditionAcceptedDate": null,
	        "deleted": false,
	        "lastLoggedInAt": null,
	        "dob": "1990-08-05",
	        "speciality": "Cardeologist, Gynocologist",
	        "credentials": "M.D., M.B.B.S.",
	        "primaryPhone": "08098745632",
	        "mobilePhone": "9874563210",
	        "faxNumber": "08098745632",
	        "address": "Old Airport Road",
	        "city": "Bangalore",
	        "state": "Karnataka",
	        "npiNumber": null
        },
        {
	        "id": 102,
	        "title": "Mr.",
	        "firstName": "Ravi",
	        "middleName": "A",
	        "lastName": "Ranjan",
	        "email": "rishabhjain+acct5@neevtech.com",
	        "gender": "M",
	        "zipcode": 560042,
	        "activated": false,
	        "langKey": "en",
	        "resetKey": null,
	        "resetDate": null,
	        "termsConditionAccepted": false,
	        "termsConditionAcceptedDate": null,
	        "deleted": false,
	        "lastLoggedInAt": null,
	        "dob": "1990-08-05",
	        "speciality": "Cardeologist, Gynocologist",
	        "credentials": "M.D., M.B.B.S.",
	        "primaryPhone": "08098745632",
	        "mobilePhone": "9874563210",
	        "faxNumber": "08098745632",
	        "address": "Old Airport Road",
	        "city": "Bangalore",
	        "state": "Karnataka",
	        "npiNumber": null
        },{
	        "id": 103,
	        "title": "Mr.",
	        "firstName": "Mark",
	        "middleName": "A",
	        "lastName": "collenn",
	        "email": "rishabhjain+acct5@neevtech.com",
	        "gender": "M",
	        "zipcode": 560042,
	        "activated": false,
	        "langKey": "en",
	        "resetKey": null,
	        "resetDate": null,
	        "termsConditionAccepted": false,
	        "termsConditionAcceptedDate": null,
	        "deleted": false,
	        "lastLoggedInAt": null,
	        "dob": "1990-08-05",
	        "speciality": "Cardeologist, Gynocologist",
	        "credentials": "M.D., M.B.B.S.",
	        "primaryPhone": "08098745632",
	        "mobilePhone": "9874563210",
	        "faxNumber": "08098745632",
	        "address": "Old Airport Road",
	        "city": "Bangalore",
	        "state": "Karnataka",
	        "npiNumber": null
        },{
	        "id": 104,
	        "title": "Mr.",
	        "firstName": "Steve",
	        "middleName": "A",
	        "lastName": "James",
	        "email": "rishabhjain+acct5@neevtech.com",
	        "gender": "M",
	        "zipcode": 560042,
	        "activated": false,
	        "langKey": "en",
	        "resetKey": null,
	        "resetDate": null,
	        "termsConditionAccepted": false,
	        "termsConditionAcceptedDate": null,
	        "deleted": false,
	        "lastLoggedInAt": null,
	        "dob": "1990-08-05",
	        "speciality": "Cardeologist, Gynocologist",
	        "credentials": "M.D., M.B.B.S.",
	        "primaryPhone": "08098745632",
	        "mobilePhone": "9874563210",
	        "faxNumber": "08098745632",
	        "address": "Old Airport Road",
	        "city": "Bangalore",
	        "state": "Karnataka",
	        "npiNumber": null
        }

    ]
  }

var doctorsLinkedToPatient = 
	{
    "hcpUsers": [
        {
	        "id": 101,
	        "title": "Mr.",
	        "firstName": "Rishabh",
	        "middleName": "A",
	        "lastName": "Jain",
	        "email": "rishabhjain+acct5@neevtech.com",
	        "gender": "M",
	        "zipcode": 560042,
	        "activated": false,
	        "langKey": "en",
	        "resetKey": null,
	        "resetDate": null,
	        "termsConditionAccepted": false,
	        "termsConditionAcceptedDate": null,
	        "deleted": false,
	        "lastLoggedInAt": null,
	        "dob": "1990-08-05",
	        "speciality": "Cardeologist, Gynocologist",
	        "credentials": "M.D., M.B.B.S.",
	        "primaryPhone": "08098745632",
	        "mobilePhone": "9874563210",
	        "faxNumber": "08098745632",
	        "address": "Old Airport Road",
	        "city": "Bangalore",
	        "state": "Karnataka",
	        "npiNumber": null
        },
        {
	        "id": 102,
	        "title": "Mr.",
	        "firstName": "Ravi",
	        "middleName": "A",
	        "lastName": "Ranjan",
	        "email": "rishabhjain+acct5@neevtech.com",
	        "gender": "M",
	        "zipcode": 560042,
	        "activated": false,
	        "langKey": "en",
	        "resetKey": null,
	        "resetDate": null,
	        "termsConditionAccepted": false,
	        "termsConditionAcceptedDate": null,
	        "deleted": false,
	        "lastLoggedInAt": null,
	        "dob": "1990-08-05",
	        "speciality": "Cardeologist, Gynocologist",
	        "credentials": "M.D., M.B.B.S.",
	        "primaryPhone": "08098745632",
	        "mobilePhone": "9874563210",
	        "faxNumber": "08098745632",
	        "address": "Old Airport Road",
	        "city": "Bangalore",
	        "state": "Karnataka",
	        "npiNumber": null
        },{
	        "id": 103,
	        "title": "Mr.",
	        "firstName": "Mark",
	        "middleName": "A",
	        "lastName": "collenn",
	        "email": "rishabhjain+acct5@neevtech.com",
	        "gender": "M",
	        "zipcode": 560042,
	        "activated": false,
	        "langKey": "en",
	        "resetKey": null,
	        "resetDate": null,
	        "termsConditionAccepted": false,
	        "termsConditionAcceptedDate": null,
	        "deleted": false,
	        "lastLoggedInAt": null,
	        "dob": "1990-08-05",
	        "speciality": "Cardeologist, Gynocologist",
	        "credentials": "M.D., M.B.B.S.",
	        "primaryPhone": "08098745632",
	        "mobilePhone": "9874563210",
	        "faxNumber": "08098745632",
	        "address": "Old Airport Road",
	        "city": "Bangalore",
	        "state": "Karnataka",
	        "npiNumber": null
        },{
	        "id": 104,
	        "title": "Mr.",
	        "firstName": "Steve",
	        "middleName": "A",
	        "lastName": "James",
	        "email": "rishabhjain+acct5@neevtech.com",
	        "gender": "M",
	        "zipcode": 560042,
	        "activated": false,
	        "langKey": "en",
	        "resetKey": null,
	        "resetDate": null,
	        "termsConditionAccepted": false,
	        "termsConditionAcceptedDate": null,
	        "deleted": false,
	        "lastLoggedInAt": null,
	        "dob": "1990-08-05",
	        "speciality": "Cardeologist, Gynocologist",
	        "credentials": "M.D., M.B.B.S.",
	        "primaryPhone": "08098745632",
	        "mobilePhone": "9874563210",
	        "faxNumber": "08098745632",
	        "address": "Old Airport Road",
	        "city": "Bangalore",
	        "state": "Karnataka",
	        "npiNumber": null
        }

    ]
  }
