var roleEnum = {
  ADMIN : 'ADMIN',
  PATIENT : 'PATIENT',
  HCP : 'HCP',
  ACCT_SERVICES : 'ACCT_SERVICES',
  ASSOCIATES : 'ASSOCIATES',
  HILLROM_ADMIN : 'HILLROM_ADMIN',
  CLINIC_ADMIN : 'CLINIC_ADMIN',
  ANONYMOUS : 'ANONYMOUS'
};

var doctorsAvailInClinic = 
	{
    "hcpUsers": [
        {
	        "id": 101,
	        "title": "Mr.",
	        "firstName": "Rishabh",
	        "middleName": "A",
	        "lastName": "Jain",
	        "email": "rishabhjain+acct5@neevtech.com",
	        "gender": "M",
	        "zipcode": 560042,
	        "activated": false,
	        "langKey": "en",
	        "resetKey": null,
	        "resetDate": null,
	        "termsConditionAccepted": false,
	        "termsConditionAcceptedDate": null,
	        "deleted": false,
	        "lastLoggedInAt": null,
	        "dob": "1990-08-05",
	        "speciality": "Cardeologist, Gynocologist",
	        "credentials": "M.D., M.B.B.S.",
	        "primaryPhone": "08098745632",
	        "mobilePhone": "9874563210",
	        "faxNumber": "08098745632",
	        "address": "Old Airport Road",
	        "city": "Bangalore",
	        "state": "Karnataka",
	        "npiNumber": null
        },
        {
	        "id": 102,
	        "title": "Mr.",
	        "firstName": "Ravi",
	        "middleName": "A",
	        "lastName": "Ranjan",
	        "email": "rishabhjain+acct5@neevtech.com",
	        "gender": "M",
	        "zipcode": 560042,
	        "activated": false,
	        "langKey": "en",
	        "resetKey": null,
	        "resetDate": null,
	        "termsConditionAccepted": false,
	        "termsConditionAcceptedDate": null,
	        "deleted": false,
	        "lastLoggedInAt": null,
	        "dob": "1990-08-05",
	        "speciality": "Cardeologist, Gynocologist",
	        "credentials": "M.D., M.B.B.S.",
	        "primaryPhone": "08098745632",
	        "mobilePhone": "9874563210",
	        "faxNumber": "08098745632",
	        "address": "Old Airport Road",
	        "city": "Bangalore",
	        "state": "Karnataka",
	        "npiNumber": null
        },{
	        "id": 103,
	        "title": "Mr.",
	        "firstName": "Mark",
	        "middleName": "A",
	        "lastName": "collenn",
	        "email": "rishabhjain+acct5@neevtech.com",
	        "gender": "M",
	        "zipcode": 560042,
	        "activated": false,
	        "langKey": "en",
	        "resetKey": null,
	        "resetDate": null,
	        "termsConditionAccepted": false,
	        "termsConditionAcceptedDate": null,
	        "deleted": false,
	        "lastLoggedInAt": null,
	        "dob": "1990-08-05",
	        "speciality": "Cardeologist, Gynocologist",
	        "credentials": "M.D., M.B.B.S.",
	        "primaryPhone": "08098745632",
	        "mobilePhone": "9874563210",
	        "faxNumber": "08098745632",
	        "address": "Old Airport Road",
	        "city": "Bangalore",
	        "state": "Karnataka",
	        "npiNumber": null
        },{
	        "id": 104,
	        "title": "Mr.",
	        "firstName": "Steve",
	        "middleName": "A",
	        "lastName": "James",
	        "email": "rishabhjain+acct5@neevtech.com",
	        "gender": "M",
	        "zipcode": 560042,
	        "activated": false,
	        "langKey": "en",
	        "resetKey": null,
	        "resetDate": null,
	        "termsConditionAccepted": false,
	        "termsConditionAcceptedDate": null,
	        "deleted": false,
	        "lastLoggedInAt": null,
	        "dob": "1990-08-05",
	        "speciality": "Cardeologist, Gynocologist",
	        "credentials": "M.D., M.B.B.S.",
	        "primaryPhone": "08098745632",
	        "mobilePhone": "9874563210",
	        "faxNumber": "08098745632",
	        "address": "Old Airport Road",
	        "city": "Bangalore",
	        "state": "Karnataka",
	        "npiNumber": null
        }

    ]
  }

var doctorsLinkedToPatient = 
	{
    "hcpUsers": [
        {
	        "id": 101,
	        "title": "Mr.",
	        "firstName": "Rishabh",
	        "middleName": "A",
	        "lastName": "Jain",
	        "email": "rishabhjain+acct5@neevtech.com",
	        "gender": "M",
	        "zipcode": 560042,
	        "activated": false,
	        "langKey": "en",
	        "resetKey": null,
	        "resetDate": null,
	        "termsConditionAccepted": false,
	        "termsConditionAcceptedDate": null,
	        "deleted": false,
	        "lastLoggedInAt": null,
	        "dob": "1990-08-05",
	        "speciality": "Cardeologist, Gynocologist",
	        "credentials": "M.D., M.B.B.S.",
	        "primaryPhone": "08098745632",
	        "mobilePhone": "9874563210",
	        "faxNumber": "08098745632",
	        "address": "Old Airport Road",
	        "city": "Bangalore",
	        "state": "Karnataka",
	        "npiNumber": null
        },
        {
	        "id": 102,
	        "title": "Mr.",
	        "firstName": "Ravi",
	        "middleName": "A",
	        "lastName": "Ranjan",
	        "email": "rishabhjain+acct5@neevtech.com",
	        "gender": "M",
	        "zipcode": 560042,
	        "activated": false,
	        "langKey": "en",
	        "resetKey": null,
	        "resetDate": null,
	        "termsConditionAccepted": false,
	        "termsConditionAcceptedDate": null,
	        "deleted": false,
	        "lastLoggedInAt": null,
	        "dob": "1990-08-05",
	        "speciality": "Cardeologist, Gynocologist",
	        "credentials": "M.D., M.B.B.S.",
	        "primaryPhone": "08098745632",
	        "mobilePhone": "9874563210",
	        "faxNumber": "08098745632",
	        "address": "Old Airport Road",
	        "city": "Bangalore",
	        "state": "Karnataka",
	        "npiNumber": null
        },{
	        "id": 103,
	        "title": "Mr.",
	        "firstName": "Mark",
	        "middleName": "A",
	        "lastName": "collenn",
	        "email": "rishabhjain+acct5@neevtech.com",
	        "gender": "M",
	        "zipcode": 560042,
	        "activated": false,
	        "langKey": "en",
	        "resetKey": null,
	        "resetDate": null,
	        "termsConditionAccepted": false,
	        "termsConditionAcceptedDate": null,
	        "deleted": false,
	        "lastLoggedInAt": null,
	        "dob": "1990-08-05",
	        "speciality": "Cardeologist, Gynocologist",
	        "credentials": "M.D., M.B.B.S.",
	        "primaryPhone": "08098745632",
	        "mobilePhone": "9874563210",
	        "faxNumber": "08098745632",
	        "address": "Old Airport Road",
	        "city": "Bangalore",
	        "state": "Karnataka",
	        "npiNumber": null
        },{
	        "id": 104,
	        "title": "Mr.",
	        "firstName": "Steve",
	        "middleName": "A",
	        "lastName": "James",
	        "email": "rishabhjain+acct5@neevtech.com",
	        "gender": "M",
	        "zipcode": 560042,
	        "activated": false,
	        "langKey": "en",
	        "resetKey": null,
	        "resetDate": null,
	        "termsConditionAccepted": false,
	        "termsConditionAcceptedDate": null,
	        "deleted": false,
	        "lastLoggedInAt": null,
	        "dob": "1990-08-05",
	        "speciality": "Cardeologist, Gynocologist",
	        "credentials": "M.D., M.B.B.S.",
	        "primaryPhone": "08098745632",
	        "mobilePhone": "9874563210",
	        "faxNumber": "08098745632",
	        "address": "Old Airport Road",
	        "city": "Bangalore",
	        "state": "Karnataka",
	        "npiNumber": null
        }

    ]
  }
var associatedClinics = 
{
    "clinics": [
        {
            "id": "HR2015000000",
            "name": "LifeLine Hospitals Main",
            "address": "Sector-58",
            "zipcode": 23651,
            "city": "Noida",
            "state": "UT",
            "phoneNumber": "2242313112",
            "faxNumber": "1131313131",
            "hillromId": "HR2015000132",
            "clinicAdminId": 9,
            "parentClinic": null,
            "deleted": true,
            "parent": true,
            "createdAt": 1438688454000
        },
        {
            "id": "HR2015000001",
            "name": "LifeLine Hospitals Child",
            "address": "Sector 78",
            "zipcode": 65412,
            "city": "Gurgaon",
            "state": "UT",
            "phoneNumber": "2143464311",
            "faxNumber": "3134648431",
            "hillromId": "HR201500123",
            "clinicAdminId": 9,
            "parentClinic": {
                "id": "HR2015000000",
                "name": "LifeLine Hospitals Main",
                "address": "Sector-58",
                "zipcode": 23651,
                "city": "Noida",
                "state": "UT",
                "phoneNumber": "2242313112",
                "faxNumber": "1131313131",
                "hillromId": "HR2015000132",
                "clinicAdminId": 9,
                "parentClinic": null,
                "deleted": true,
                "parent": true,
                "createdAt": 1438688454000
            },
            "deleted": false,
            "parent": false,
            "createdAt": 1438688532000
        },
        {
            "id": "HR2015000002",
            "name": "LifeLine Hospitals Main",
            "address": "Sector-58",
            "zipcode": 23651,
            "city": "Noida",
            "state": "UT",
            "phoneNumber": "2242313112",
            "faxNumber": "1131313131",
            "hillromId": "HR2015000132",
            "clinicAdminId": 9,
            "parentClinic": null,
            "deleted": true,
            "parent": true,
            "createdAt": 1438688454000
        },
        {
            "id": "HR2015000003",
            "name": "LifeLine Hospitals Child",
            "address": "Sector 78",
            "zipcode": 65412,
            "city": "Gurgaon",
            "state": "UT",
            "phoneNumber": "2143464311",
            "faxNumber": "3134648431",
            "hillromId": "HR201500123",
            "clinicAdminId": 9,
            "parentClinic": {
                "id": "HR2015000000",
                "name": "LifeLine Hospitals Main",
                "address": "Sector-58",
                "zipcode": 23651,
                "city": "Noida",
                "state": "UT",
                "phoneNumber": "2242313112",
                "faxNumber": "1131313131",
                "hillromId": "HR2015000132",
                "clinicAdminId": 9,
                "parentClinic": null,
                "deleted": true,
                "parent": true,
                "createdAt": 1438688454000
            },
            "deleted": false,
            "parent": false,
            "createdAt": 1438688532000
        }
    ],
    "message": "Associated clinics with patient fetched successfully."
}
var careGivers = {
    "caregivers": [
        {
            "id": 16,
            "title": "Mr.",
            "firstName": "Nagendra",
            "middleName": "",
            "lastName": "Nag",
            "email": "rishabhjain+CG_hcp@neevtech.com",
            "gender": null,
            "zipcode": 56236,
            "activated": true,
            "langKey": "en",
            "resetKey": "66945600887392212927",
            "resetDate": 1438577209000,
            "termsConditionAccepted": true,
            "termsConditionAcceptedDate": 1438576050000,
            "authorities": [
                {
                    "name": "HCP"
                }
            ],
            "deleted": true,
            "lastLoggedInAt": 1438576050000,
            "dob": null,
            "hillromId": null,
            "speciality": "Optho",
            "credentials": "123456",
            "primaryPhone": "7654123002",
            "mobilePhone": "8657416856",
            "faxNumber": "6498562305",
            "address": "Dickenson Road",
            "city": "Blr",
            "state": "AL",
            "npiNumber": "986532",
            "clinics": []
        },
        {
            "id": 16,
            "title": "Mr.",
            "firstName": "Nagendra",
            "middleName": "",
            "lastName": "Nag",
            "email": "rishabhjain+CG_hcp@neevtech.com",
            "gender": null,
            "zipcode": 56236,
            "activated": true,
            "langKey": "en",
            "resetKey": "66945600887392212927",
            "resetDate": 1438577209000,
            "termsConditionAccepted": true,
            "termsConditionAcceptedDate": 1438576050000,
            "authorities": [
                {
                    "name": "HCP"
                }
            ],
            "deleted": true,
            "lastLoggedInAt": 1438576050000,
            "dob": null,
            "hillromId": null,
            "speciality": "Optho",
            "credentials": "123456",
            "primaryPhone": "7654123002",
            "mobilePhone": "8657416856",
            "faxNumber": "6498562305",
            "address": "Dickenson Road",
            "city": "Blr",
            "state": "AL",
            "npiNumber": "986532",
            "clinics": []
        }
    ],
    "message": "Caregiver Users fetched successfully."
}