package com.hillrom.vest.repository;

import static com.hillrom.vest.security.AuthoritiesConstants.HCP;
import static com.hillrom.vest.security.AuthoritiesConstants.PATIENT;
import static com.hillrom.vest.util.RelationshipLabelConstants.SELF;

import java.util.List;
import java.util.Optional;

import javax.transaction.Transactional;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.jpa.repository.query.Procedure;
import org.springframework.data.querydsl.QueryDslPredicateExecutor;
import org.springframework.data.repository.query.Param;

import com.hillrom.vest.domain.Clinic;
import com.hillrom.vest.web.rest.dto.ClinicStatsNotificationVO;

/**
 * Spring Data JPA repository for the Clinic entity.
 */
public interface ClinicRepository extends JpaRepository<Clinic,String> , QueryDslPredicateExecutor<Clinic> {
	
	 @Query("from Clinic clinic where  "
				+ "( LOWER(clinic.name) like LOWER(:queryString) or "
				+ "LOWER(clinic.hillromId) like LOWER(:queryString) or "
				+ "LOWER(clinic.zipcode) like LOWER(:queryString) or "
				+ "LOWER(clinic.state) like LOWER(:queryString)) and "
				+ "clinic.deleted in (:isDeleted)")
	Page<Clinic> findBy(@Param("queryString") String queryString,
			@Param("isDeleted")List<Boolean> isDeleted,Pageable pageable); 

    Optional<Clinic> findOneByName(String name);
    
    @Override
    void delete(Clinic t);

    /**
	 * This returns hillromId of the patient from stored procedure.
	 * @return String hillromId
	 */
	@Procedure(outputParameterName="hillrom_id",procedureName="get_next_clinic_hillromid")
	@Transactional
	String id();

	@Query("from Clinic clinic where clinic.clinicAdminId IS NOT NULL")
	List<Clinic> findAllWithClinicAdmins();
	
	@Query("from Clinic clinic where LOWER(clinic.hillromId) = ?1")
    Optional<Clinic> findOneByHillromId(String hillromId);
	
	@Query("from Clinic clinic where clinic.clinicAdminId = ?1")
    List<Clinic> findByClinicAdminId(Long clinicAdminId);

	@Query("from Clinic clinic where clinic.deleted = ?1 and clinic.clinicPatientAssoc IS NOT EMPTY and clinic.users IS NOT EMPTY or clinic.clinicAdminId IS NOT NULL")
	List<Clinic> findByDeletedAndClinicPatientAssocIsNotEmpty(boolean isDeleted);

	/*@Query(nativeQuery=true,
			value=" select puserid,pfirstname,plastname,hcp_id,huserid,CONCAT(hlastName,' ', hfirstName) as hname,clinicId,clinicname,clinicadminid,pc.missed_therapy_count,pc.is_settings_deviated,pc.is_hmr_compliant,"
					+ " nhn, sdn,mtn,hemail,caname,a_cahmr,a_casdn,a_camtn,a_caemail,clinicadherencesetting from ( "
					+ " select user.id as puserid,user.first_name as pfirstName,user.last_name as plastName,upa_hcp.user_id as hcp_id"
					+ " from USER user join USER_AUTHORITY user_authority on user_authority.user_id = user.id and user_authority.authority_name = '"+PATIENT+"'"
					+ " join USER_PATIENT_ASSOC  upa on user.id= upa.user_id and upa.relation_label = '"+SELF+"' "
					+ " join PATIENT_INFO patInfo on upa.patient_id = patInfo.id "
					+ " join USER_PATIENT_ASSOC upa_hcp on patInfo.id = upa_hcp.patient_id "
					+ " where user.is_deleted = 0 and user.activated=1) as associated_patient, "
					+ " (select huser.id as huserid,huser.first_name as hfirstName,huser.last_name as hlastName,huser.email as hemail,clinic.id as clinicid,clinic.name as clinicname,eua.user_id AS clinicadminid, clinic.adherence_setting as clinicadherencesetting, "
					+ " (select CONCAT(ca.last_name,' ', ca.first_name)  from USER ca where id = eua.user_id) as caname, "
					+ " (select ca.email from USER ca where id = eua.user_id) as a_caemail, "
					+ " (select cahmr.non_hmr_notification  from USER cahmr where id = eua.user_id) as a_cahmr, "
					+ " (select casdn.setting_deviation_notification  from USER casdn where id = eua.user_id) as a_casdn, "
					+ " (select camtn.missed_therapy_notification  from USER camtn where id = eua.user_id) as a_camtn, "
					+ " huser.non_hmr_notification as nhn, huser.setting_deviation_notification as sdn,huser.missed_therapy_notification as mtn from USER huser "
					+ " join USER_AUTHORITY user_authorityh on user_authorityh.user_id = huser.id and user_authorityh.authority_name = '"+HCP+"' "
					+ " left outer join CLINIC_USER_ASSOC user_clinic on user_clinic.users_id = huser.id "
					+ " left outer join CLINIC clinic on user_clinic.clinics_id = clinic.id and user_clinic.users_id = huser.id "
					+ " LEFT OUTER JOIN ENTITY_USER_ASSOC eua ON eua.entity_id = clinic.id and eua.user_id = huser.id "
					+ " where clinic.is_deleted=0 and (huser.non_hmr_notification=1 or huser.setting_deviation_notification=1 or huser.missed_therapy_notification=1 )) "
					+ " as associated_hcp, PATIENT_COMPLIANCE pc "
					+ " where puserid = pc.user_id AND pc.date=SUBDATE(CURDATE(),1) and associated_patient.hcp_id = associated_hcp.huserid ")
	List<Object[]> findPatientStatisticsClinicForActiveClinics();
	*/
	@Query(nativeQuery=true,
			 value="select puserid,pfirstname,plastname,cgvr_id,CONCAT(clastName,' ', cfirstName) as cname,pc.missed_therapy_count,pc.is_settings_deviated,pc.is_hmr_compliant,"
					+"cemail, isMissedTherapyNotification,settingDeviationNotification, nonHmrNotification  from ( "
					+"select user.id as puserid,user.first_name as pfirstName,user.last_name as plastName,upa_cgvr.user_id as cgvr_id "
					+"from USER user  "
					+"join USER_AUTHORITY user_authority on user_authority.user_id = user.id and user_authority.authority_name = 'PATIENT' "
					+"join USER_PATIENT_ASSOC  upa on user.id= upa.user_id and upa.relation_label = 'SELF'  "
					+"join PATIENT_INFO patInfo on upa.patient_id = patInfo.id  "
					+"join USER_PATIENT_ASSOC upa_cgvr on patInfo.id = upa_cgvr.patient_id  "
					+"where user.is_deleted = 0 and user.activated=1) as associated_patient,  "
					+"(select cuser.id as cuserid,cuser.first_name as cfirstName,cuser.last_name as clastName,cuser.email as cemail, "
					+"missed_therapy_notification as isMissedTherapyNotification, setting_deviation_notification as settingDeviationNotification, "
					+ "non_hmr_notification as nonHmrNotification from USER cuser  "
					+"join USER_AUTHORITY user_authorityc on user_authorityc.user_id = cuser.id and user_authorityc.authority_name = 'CARE_GIVER')  "
					+"as associated_cgvr, PATIENT_COMPLIANCE pc  where  "
					+"puserid = pc.user_id AND pc.date=SUBDATE(CURDATE(),1) and  "
					+"associated_patient.cgvr_id = associated_cgvr.cuserid ")
	List<Object[]> findPatientStatisticsCareGiver();
	
	//start:HILL-2004
	@Query("from Clinic clinic where clinic.id in :clinicIds order by clinic.adherenceSettingModifiedDte desc")
	List<Clinic> findPatientLastModifiedAdherenceSetting(@Param("clinicIds")List<String> clinicIds);
  //start:HILL-2004
	
	@Query(nativeQuery=true,
			 value=" Select dtype,if(count is null,0,count) from "
			 		+ " (SELECT type_code as dtype FROM HILLROM_TYPE_CODE_VALUES"
			 		+ " where type = 'patient_device_type') a left outer join "
			 		+ "	(select PDA.device_type as pdtype,count(*) as count "
			 		+ " from CLINIC_PATIENT_ASSOC CPA "
			 		+ " left outer join "
			 		+ "  ((select patient_id,device_type "
			 		+ "		from PATIENT_DEVICES_ASSOC where is_active=1) " 
			 		+ "			union "
			 		+ "	  (select patient_id,'ALL' as device_type "
			 		+ "		from PATIENT_DEVICES_ASSOC " 
			 		+ "		where patient_type='CD' and is_active=1 "
			 		+ "		group by patient_id)) PDA "

			 		+ " on CPA.patient_id=PDA.patient_id "
			 		+ " where CPA.is_active=1 and clinic_id = :clinicId "
			 		+ " group by PDA.device_type "
			 		+ " order by count desc) b on a.dtype = b.pdtype " )
	List<Object[]> findByDeviceTypeAndPatientCount(@Param("clinicId")String clinicId);
	
	@Query(nativeQuery=true,
			value=	"SELECT "
					+ "   'HCP', "
					+ "   puserid, "
					+ "   pfirstname, "
					+ "   plastname, "
					+ "   huserid, "
					+ "   Concat(hlastname, ' ', hfirstname) AS hname, "
					+ "   clinicid, "
					+ "   clinicname, "
					+ "   pc.date, "
					+ "   pc.missed_therapy_count, "
					+ "   pc.is_settings_deviated, "
					+ "   pc.is_hmr_compliant, "
					+ "   nhn, sdn,mtn,nhnf,sdnf,mtnf,hemail,clinicadherencesetting "
					+ "from "
					+ "   ( "
					+ "      SELECT "
					+ "         USER.id AS puserid, "
					+ "         USER.first_name AS pfirstname, "
					+ "         USER.last_name AS plastname, "
					+ "         cpa.clinic_id as userclinicId "
					+ "      from "
					+ "         USER USER "
					+ "         join "
					+ "            USER_AUTHORITY user_authority "
					+ "            on user_authority.user_id = USER.id "
					+ "            and user_authority.authority_name = 'PATIENT' "
					+ "         JOIN "
					+ "            USER_PATIENT_ASSOC upa "
					+ "            ON USER.id = upa.user_id "
					+ "            AND upa.relation_label = 'SELF' "
					+ "         join "
					+ "            PATIENT_INFO patInfo "
					+ "            on upa.patient_id = patInfo.id "
					+ "         JOIN "
					+ "            USER_PATIENT_ASSOC upa_pat "
					+ "            ON patInfo.id = upa_pat.patient_id "
					+ "         LEFT OUTER JOIN "
					+ "            CLINIC_PATIENT_ASSOC cpa "
					+ "            ON cpa.patient_id = upa_pat.patient_id "
					+ "      where "
					+ "         USER.is_deleted = 0 "
					+ "         and USER.activated = 1 "
					+ "   ) "
					+ "   as associated_patient, "
					+ "   ( "
					+ "      SELECT "
					+ "         huser.id AS huserid, "
					+ "         huser.first_name AS hfirstname, "
					+ "         huser.last_name AS hlastname, "
					+ "         huser.email AS hemail, "
					+ "         clinic.id AS clinicid, "
					+ "         clinic.NAME AS clinicname, "
					+ "         clinic.adherence_setting AS clinicadherencesetting, "
					+ "         huser.non_hmr_notification AS nhn, "
					+ "         huser.setting_deviation_notification AS sdn, "
					+ "         huser.missed_therapy_notification AS mtn , "					
					+ "			huser.missed_therapy_notification_freq AS mtnf, "
					+ "			huser.non_hmr_notification_freq AS nhnf, "
					+ "			huser.setting_deviation_notification_freq AS sdnf "
					+ "      FROM "
					+ "         USER huser "
					+ "         join "
					+ "            USER_AUTHORITY user_authorityh "
					+ "            on user_authorityh.user_id = huser.id "
					+ "            and user_authorityh.authority_name = 'HCP' "
					+ "         LEFT OUTER JOIN "
					+ "            CLINIC_USER_ASSOC user_clinic "
					+ "            ON user_clinic.users_id = huser.id "
					+ "         left outer join "
					+ "            CLINIC clinic "
					+ "            on user_clinic.clinics_id = clinic.id "
					+ "            and user_clinic.users_id = huser.id "
					+ "      where "
					+ "         clinic.is_deleted = 0 "
					+ "         and "
					+ "         ( "
					+ "            huser.non_hmr_notification = 1 "
					+ "            or huser.setting_deviation_notification = 1 "
					+ "            or huser.missed_therapy_notification = 1 "
					+ "         ) "
					+ "   ) "
					+ "   AS associated_hcp, "
					+ "   PATIENT_COMPLIANCE pc "
					+ "where "
					+ "   puserid = pc.user_id "
					+ "   AND pc.date between DATE_SUB(curdate(), INTERVAL 1 WEEK) and CURDATE() "
					+ "   and associated_patient.userclinicId = associated_hcp.clinicid "
					+ "UNION "
					+ "SELECT "
					+ "   'CLINIC_ADMIN', "
					+ "   puserid, "
					+ "   pfirstname, "
					+ "   plastname, "
					+ "   causerid, "
					+ "   Concat(causerlastname, ' ', causerfirstname) AS caname, "
					+ "   clinicid, "
					+ "   clinicname, "
					+ "   pc.date, "
					+ "   pc.missed_therapy_count, "
					+ "   pc.is_settings_deviated, "
					+ "   pc.is_hmr_compliant, "
					+ "   nhn, sdn,mtn,nhnf,sdnf,mtnf,hemail,clinicadherencesetting "
					+ "from "
					+ "   ( "
					+ "      SELECT "
					+ "         USER.id AS puserid, "
					+ "         USER.first_name AS pfirstname, "
					+ "         USER.last_name AS plastname, "
					+ "         cpa.clinic_id as userclinicId "
					+ "      from "
					+ "         USER USER "
					+ "         join "
					+ "            USER_AUTHORITY user_authority "
					+ "            on user_authority.user_id = USER.id "
					+ "            and user_authority.authority_name = 'PATIENT' "
					+ "         JOIN "
					+ "            USER_PATIENT_ASSOC upa "
					+ "            ON USER.id = upa.user_id "
					+ "            AND upa.relation_label = 'SELF' "
					+ "         join "
					+ "            PATIENT_INFO patInfo "
					+ "            on upa.patient_id = patInfo.id "
					+ "         JOIN "
					+ "            USER_PATIENT_ASSOC upa_pat "
					+ "            ON patInfo.id = upa_pat.patient_id "
					+ "         LEFT OUTER JOIN "
					+ "            CLINIC_PATIENT_ASSOC cpa "
					+ "            ON cpa.patient_id = upa_pat.patient_id "
					+ "      where "
					+ "         USER.is_deleted = 0 "
					+ "         and USER.activated = 1 "
					+ "   ) "
					+ "   as associated_patient, "
					+ "   ( "
					+ "      SELECT "
					+ "         causer.id AS causerid, "
					+ "         causer.first_name AS causerfirstname, "
					+ "         causer.last_name AS causerlastname, "
					+ "         causer.email AS causeremail, "
					+ "         clinic.id AS clinicid, "
					+ "         clinic.NAME AS clinicname, "
					+ "         clinic.adherence_setting AS clinicadherencesetting, "
					+ "         causer.non_hmr_notification AS nhn, "
					+ "         causer.setting_deviation_notification AS sdn, "
					+ "         causer.missed_therapy_notification AS mtn , "
					+ "			causer.missed_therapy_notification_freq AS mtnf, "
					+ "			causer.non_hmr_notification_freq AS nhnf, "
					+ "			causer.setting_deviation_notification_freq AS sdnf "
					+ "      FROM "
					+ "         USER causer "
					+ "         join "
					+ "            USER_AUTHORITY user_authorityh "
					+ "            on user_authorityh.user_id = causer.id "
					+ "            and user_authorityh.authority_name = 'CLINIC_ADMIN' "
					+ "         LEFT OUTER JOIN "
					+ "            ENTITY_USER_ASSOC eua "
					+ "            ON eua.user_id = causer.id "
					+ "         left outer join "
					+ "            CLINIC clinic "
					+ "            on eua.entity_id = clinic.id "
					+ "            and eua.entity_id = clinic.id "
					+ "      where "
					+ "         clinic.is_deleted = 0 "
					+ "         and "
					+ "         ( "
					+ "            causer.non_hmr_notification = 1 "
					+ "            or causer.setting_deviation_notification = 1 "
					+ "            or causer.missed_therapy_notification = 1 "
					+ "         ) "
					+ "   ) "
					+ "   AS associated_cadmin, "
					+ "   PATIENT_COMPLIANCE pc "
					+ "where "
					+ "   puserid = pc.user_id "
					+ "   AND pc.date between DATE_SUB(curdate(), INTERVAL 1 WEEK) and CURDATE() "
					+ "   and associated_patient.userclinicId = associated_cadmin.clinicid")
	List<Object[]> findPatientStatisticsClinicForActiveClinics();
	
	
	@Query(nativeQuery=true,
			 value= "select puserid,pfirstname,plastname,cgvr_id,CONCAT(clastName,' ', cfirstName) as cname,pc.missed_therapy_count,pc.is_settings_deviated,pc.is_hmr_compliant, "
					 + "cemail, "
					 + "isMissedTherapyNotification, "
					 + "settingDeviationNotification, "
					 + "nonHmrNotification, "
					 + "missedTherapyNotificationFreq, "
					 + "  nonHmrNotificationFreq, "
					 + "settingDeviationNotificationFreq "
					 + "from "
					 + "(select user.id as puserid,user.first_name as pfirstName,user.last_name as plastName,upa_cgvr.user_id as cgvr_id "
					 + "from USER user "
					 + " "
					 + "join USER_AUTHORITY user_authority on user_authority.user_id = user.id and user_authority.authority_name = 'PATIENT' "
					 + "join USER_PATIENT_ASSOC  upa on user.id= upa.user_id and upa.relation_label = 'SELF' "
					 + "join PATIENT_INFO patInfo on upa.patient_id = patInfo.id "
					 + "join USER_PATIENT_ASSOC upa_cgvr on patInfo.id = upa_cgvr.patient_id "
					 + "where user.is_deleted = 0 and user.activated=1) as associated_patient, "
					 + " "
					 + "(select cuser.id as cuserid, "
					 + "cuser.first_name as cfirstName, "
					 + "cuser.last_name as clastName, "
					 + "cuser.email as cemail, "
					 + "cuser.missed_therapy_notification as isMissedTherapyNotification, "
					 + "cuser.setting_deviation_notification as settingDeviationNotification, "
					 + "cuser.non_hmr_notification as nonHmrNotification, "
					 + "cuser.missed_therapy_notification_freq as missedTherapyNotificationFreq, "
					 + "cuser.non_hmr_notification_freq as nonHmrNotificationFreq, "
					 + "cuser.setting_deviation_notification_freq as settingDeviationNotificationFreq "
					 + "from USER cuser "
					 + " "
					 + "join USER_AUTHORITY user_authorityc on user_authorityc.user_id = cuser.id and user_authorityc.authority_name = 'CARE_GIVER') "
					 + "as associated_cgvr, PATIENT_COMPLIANCE pc  where "
					 + "puserid = pc.user_id AND pc.date between DATE_SUB(curdate(), INTERVAL 1 WEEK) and CURDATE() AND "
					 + "associated_patient.cgvr_id = associated_cgvr.cuserid")
	List<Object[]> findPatientStatisticsCareGiverDetails();
	
	
	@Query(nativeQuery=true,
			value=	 "SELECT 'HCP', "
					+ "       puserid, "
					+ "       pfirstname, "
					+ "       plastname, "
					+ "       huserid, "
					+ "              Concat(hlastname,' ', hfirstname) AS hname, "
					+ "       clinicid, "
					+ "       clinicname, "
					+ "       pc.date, "
					+ "       pc.missed_therapy_count, "
					+ "       pc.is_settings_deviated, "
					+ "       pc.is_hmr_compliant, "
					+ "       nhn, sdn,mtn,nhnf,sdnf,mtnf,hemail,clinicadherencesetting "
					+ "	    "
					+ "		 "
					+ " "
					+ "from "
					+ "                (SELECT "
					+ "                                USER.id         AS puserid, "
					+ "       USER.first_name AS pfirstname, "
					+ "       USER.last_name  AS plastname, "
					+ "                                cpa.clinic_id as userclinicId "
					+ "                                 "
					+ "                from "
					+ "                                USER USER "
					+ "                join "
					+ "                                USER_AUTHORITY user_authority on user_authority.user_id = USER.id and user_authority.authority_name = 'PATIENT' "
					+ "                JOIN "
					+ "                                USER_PATIENT_ASSOC upa ON     USER.id= upa.user_id AND    upa.relation_label = 'SELF' "
					+ "                join "
					+ "                                PATIENT_INFO patInfo on upa.patient_id = patInfo.id "
					+ "                JOIN "
					+ "                                USER_PATIENT_ASSOC upa_pat ON     patInfo.id = upa_pat.patient_id "
					+ "                LEFT OUTER JOIN "
					+ "                                CLINIC_PATIENT_ASSOC cpa ON cpa.patient_id = upa_pat.patient_id "
					+ "                where "
					+ "                                USER.is_deleted = 0 and USER.activated=1 ) as associated_patient, "
					+ "                (SELECT          huser.id                 AS huserid, "
					+ "                                                                   huser.first_name         AS hfirstname, "
					+ "                                                                   huser.last_name          AS hlastname, "
					+ "                                                                   huser.email              AS hemail, "
					+ "                                                                   clinic.id                AS clinicid, "
					+ "                                                                   clinic.NAME              AS clinicname, "
					+ "                                                                   clinic.adherence_setting AS clinicadherencesetting, "
					+ "                                                                                huser.non_hmr_notification AS nhn, "
					+ "                                                                                huser.setting_deviation_notification AS sdn, "
					+ "                                                                                huser.missed_therapy_notification AS mtn, "
					+ "																huser.missed_therapy_notification_freq AS mtnf, "
					+ "																huser.non_hmr_notification_freq AS nhnf, "
					+ "														huser.setting_deviation_notification_freq AS sdnf "
					+ " "
					+ "				FROM "
					+ " "
					+ "                                USER huser "
					+ "                join "
					+ "                                USER_AUTHORITY user_authorityh on user_authorityh.user_id = huser.id "
					+ "                                                                                                and user_authorityh.authority_name = 'HCP' "
					+ "                LEFT OUTER JOIN "
					+ "                                CLINIC_USER_ASSOC user_clinic ON user_clinic.users_id = huser.id "
					+ "                left outer join "
					+ "                                CLINIC clinic on user_clinic.clinics_id = clinic.id "
					+ "                                                and user_clinic.users_id = huser.id "
					+ "                where "
					+ "                                clinic.is_deleted=0 and "
					+ "                                (huser.non_hmr_notification=1 or huser.setting_deviation_notification=1 "
					+ "                                                                or huser.missed_therapy_notification=1 ) ) AS associated_hcp,PATIENT_COMPLIANCE pc "
					+ "where puserid = pc.user_id "
					+ "AND pc.date between DATE_SUB(curdate(), INTERVAL 1 WEEK) and CURDATE() "
					+ "and "
					+ "associated_patient.userclinicId = associated_hcp.clinicid "
					+ " "
					+ "UNION "
					+ " "
					+ "SELECT 'CLINIC_ADMIN', "
					+ "                                puserid, "
					+ "       pfirstname, "
					+ "       plastname, "
					+ "       causerid, "
					+ "              Concat(causerlastname,' ', causerfirstname) AS caname, "
					+ "       clinicid, "
					+ "       clinicname, "
					+ "                   pc.date, "
					+ "       pc.missed_therapy_count, "
					+ "       pc.is_settings_deviated, "
					+ "       pc.is_hmr_compliant, "
					+ "       nhn, sdn,mtn,nhnf,sdnf,mtnf,causeremail,clinicadherencesetting "
					+ "from "
					+ "                (SELECT "
					+ "                                USER.id         AS puserid, "
					+ "       USER.first_name AS pfirstname, "
					+ "       USER.last_name  AS plastname, "
					+ "                                cpa.clinic_id as userclinicId "
					+ "                                 "
					+ "                from "
					+ "                                USER USER "
					+ "                join "
					+ "                                USER_AUTHORITY user_authority on user_authority.user_id = USER.id and user_authority.authority_name = 'PATIENT' "
					+ "                JOIN "
					+ "                                USER_PATIENT_ASSOC upa ON     USER.id= upa.user_id AND    upa.relation_label = 'SELF' "
					+ "                join "
					+ "                                PATIENT_INFO patInfo on upa.patient_id = patInfo.id "
					+ "                JOIN "
					+ "                                USER_PATIENT_ASSOC upa_pat ON     patInfo.id = upa_pat.patient_id "
					+ "                LEFT OUTER JOIN "
					+ "                                CLINIC_PATIENT_ASSOC cpa ON cpa.patient_id = upa_pat.patient_id "
					+ "                where "
					+ "                                USER.is_deleted = 0 and USER.activated=1 ) as associated_patient, "
					+ "                (SELECT          causer.id                 AS causerid, "
					+ "                                                                   causer.first_name         AS causerfirstname, "
					+ "                                                                   causer.last_name          AS causerlastname, "
					+ "                                                                   causer.email              AS causeremail, "
					+ "                                                                   clinic.id                AS clinicid, "
					+ "                                                                   clinic.NAME              AS clinicname, "
					+ "                                                                   clinic.adherence_setting AS clinicadherencesetting, "
					+ "                                                                                causer.non_hmr_notification AS nhn, "
					+ "                                                                                causer.setting_deviation_notification AS sdn, "
					+ "                                                                                causer.missed_therapy_notification AS mtn, "
					+ "																	causer.missed_therapy_notification_freq AS mtnf, "
					+ "																		causer.non_hmr_notification_freq AS nhnf, "
					+ "																causer.setting_deviation_notification_freq AS sdnf "
					+ " "
					+ "                FROM "
					+ "                                USER causer "
					+ "                join "
					+ "                                USER_AUTHORITY user_authorityh on user_authorityh.user_id = causer.id "
					+ "                                                                                                and user_authorityh.authority_name = 'CLINIC_ADMIN' "
					+ "                LEFT OUTER JOIN "
					+ "                                ENTITY_USER_ASSOC eua ON  eua.user_id = causer.id "
					+ "                left outer join "
					+ "                                CLINIC clinic on eua.entity_id = clinic.id and eua.entity_id = clinic.id "
					+ "                                 "
					+ "                where "
					+ "                                 clinic.is_deleted=0 "
					+ "                                and (causer.non_hmr_notification=1 or causer.setting_deviation_notification=1 "
					+ "                                                                or causer.missed_therapy_notification=1 ) ) AS associated_cadmin,PATIENT_COMPLIANCE pc "
					+ "where puserid = pc.user_id "
					+ "AND pc.date between DATE_SUB(curdate(), INTERVAL 1 WEEK) and CURDATE() "
					+ "and "
					+ "associated_patient.userclinicId = associated_cadmin.clinicid")
	List<Object[]> findPatientStatisticsClinicForActiveClinicsForWeek();
	
	@Query(nativeQuery=true,
			 value= "Select us.*,ua.authority_name,group_concat(cua.clinics_id),group_concat(cpa.clinic_id),group_concat(eua.entity_id) "
					+ " ,group_concat(cl.is_message_opted + \"\") "
					+ "from "
					+ "	USER us "
					+ "join "
					+ "	USER_AUTHORITY ua on ua.user_id = us.id and ua.authority_name in ('PATIENT','HCP','CLINIC_ADMIN') "
					+ "left outer join "
					+ "	CLINIC_USER_ASSOC cua on cua.users_id = us.id "
					+ "left outer join "
					+ "	USER_PATIENT_ASSOC upa on upa.user_id = us.id  and upa.relation_label = 'Self' "
					+ "left outer join "
					+ "	CLINIC_PATIENT_ASSOC cpa on cpa.patient_id = upa.patient_id  and ua.authority_name = 'PATIENT' "
					+ "left outer join "
					+ "	ENTITY_USER_ASSOC eua on eua.user_id = us.id and eua.user_role = 'CLINIC_ADMIN' and ua.authority_name = 'CLINIC_ADMIN' "
					+ "left outer join CLINIC cl on "
					+ "((cl.id = cua.clinics_id and ua.authority_name = 'HCP') OR (cl.id = cpa.clinic_id and ua.authority_name = 'PATIENT') "
					+ "OR (cl.id = eua.entity_id and ua.authority_name = 'CLINIC_ADMIN')) "
					+ "where "
					+ "	us.id in (:userId) "
					+ "group by us.id")
	List<Object[]> findByUserId(@Param("userId") String userId);
}
